### ISSUE TITLE
Issue test by Frank Hu

### ISSUE THREAD

**Issue by mofhu** [Frank-the-Obscure/iDoulist#1]
Issue test by Frank Hu

GitHub provides many tool for programming!

**Comment by mofhu** [comment]
e.g. we can talk about a bug here.

**Comment by mrLuyao** [comment]
ao～

**Comment by mrLuyao** [comment]
ao～

**Comment by mofhu** [comment]
嗷嗷嗷,试试中文

**Comment by zshaolin** [comment]
test

**Comment by bonjourup** [comment]
在哪里认领？

**Comment by mofhu** [comment]
@huhu8 在对应 issue 下面说话即可.但我不确定 collaborator 有没有 assignee 的权限,我可以把任务 assign 给某个人解决

**Comment by mofhu** [comment]
@huhu8 已测试, 你们应该也可以 assign. 在右侧点 assignee 选人即可
