### ISSUE TITLE
Function1-minimal viable product

### ISSUE THREAD

**Issue by mofhu** [Frank-the-Obscure/iDoulist#13]
通过 function 0 我们小试牛刀，进行了基本的工程尝试，并在原则上可把一个豆列的内容抓取到本地。
在 function 1 中，我们将开放豆瓣并不支持的`比较豆列`功能，也就是说，这个功能将能给我们带来一些更为实际的帮助
- 功能1: 对比两个/多个豆列内容
  - 应用场景: `开智群的哪些书我没有看过?`, `我和阳老的心理学阅读有哪些交集?`
  - 输入: 两个豆列链接 A B
  - 输出: AB的交/并,(A-B)等

**Comment by nicetag** [comment]
'''
搜了一下list的差集、并集和交集怎么在代码中体现
 不过有个问题是，我还没搞懂被比较的list们怎么导入，按说应该输入的是，
 从`功能 0` 输入豆列后导出的url们
'''

# -_\- coding: utf-8 -_-

global a,b

output_list_1 = ["http://book.douban.com/subject/20271917/","http://book.douban.com/subject/6509801/","http://book.douban.com/subject/6061658/"] #左边几个是例子
output_list_2 = ["http://book.douban.com/subject/6509801/"] #左边一个是例子
a = output_list_1
b = output_list_2

# a - b  or  b－a

ret = list(set(a) ^ set(b))
print ret

# a U b

print list(set(a).union(set(b)))

# a^b

tmp = [val for val in a if val in b]
print tmp

**Comment by nicetag** [comment]
嗯。。忘了这里是默认markdown的，贴上有点吓人

**Comment by mofhu** [comment]
一个参考实现思路:
两次调用 `doulist_url_to_list(doulist_url)` 这个函数, 把返回值分别赋值给 `list_a`, `list_b`
输出端也可以调用功能0 的轮子呀, 就是输出的文字要改一改啦

**Comment by mofhu** [comment]
另外, 建议: 已有的代码段, 想方设法先用指定的输入测试
比如 就先写两行赋值语句测试一下, 看看输出和自己预想的是不是一致?
如果是, 原则上就至少是可行的原型了! 也许就有心流 get:)
如果不是, 哪个应该输出的元素没输出, 或者是不该输出的元素输出了?
用标准输入测试, 问题出在哪里是比较容易判断的. 如果一上来就用 url 测试, 可能查错的成本比较高!

**Comment by mofhu** [comment]
``` python
output_list = ['http://book.douban.com/subject/1139336/', 
                'http://book.douban.com/subject/25724948/']
print 'iDoulist: your input doulist link contains: ', output_list
```

上面是我用来测试 output in CLI 的代码段, 供参考

睡前最后补充: 找一个最容易改的模块,单独测试可用,就可以作为`重要更新`推送了!

**Comment by nicetag** [comment]
可以弱弱地表示一下其实没看懂吗？（： 
迷失在别的程序员的知识海洋里是很正常的一件事情。 
                                                   ——笨办法学python

**Comment by mofhu** [comment]
今天早上我再看自己写的也不是太懂，果然 talk is cheap， 哈哈
还是写的不太清楚，下面我试着用 show the code 的方式来写

假设我来写，不妨先解决process模块——我感觉这个最容易写：
那么，我们只写process模块时，就要先假定已经解决了导入问题，即**已有**两个正确导入的 list: list1, list2
如:`list1 =['http://book.douban.com/subject/1139336/', 'http://book.douban.com/subject/25724948/']`, `list2 = ['http://book.douban.com/subject/25724948/','http://book.douban.com/subject/6709809/','http://book.douban.com/subject/24749465/','http://book.douban.com/subject/10770850/']`
注意这里的元素内容不一定要是合法的书籍链接哦！(为什么？)
完全可以是: `list1 = ['a','b','c'], list2 = ['b', 'd']`

下一步即写函数， 如合并函数的例子，我就不找库了，随便写个能用的：

``` python
list_a = ['a','b','c']
list_b = ['b', 'd']

def combine(list1, list2):
    list_combine = list1
    for i in list2:
        list_combine.append(i)
    remove_duplicate_element(list_combine) #注意这里我重用了已有的轮子(去重函数)
    return list_combine

def remove_duplicate_element(list):
    i = 0
    while i <= len(list) - 1:
        j = i + 1
        while j <= len(list) - 1:
            if list[i] == list[j]:
                del list[j]
            j += 1
        i += 1

print list_a
print list_b

print combine(list_a, list_b)
```

测试结果`http://www.codeskulptor.org/#user40_HUjdivgYkk_0.py`

```
['a', 'b', 'c']
['b', 'd']
['a', 'b', 'c', 'd']
```

下面再用实际豆列内容测试一下，无误的话就完全可以推送一次（比如标记为function1分支）.
这次推送的更新内容即， 实现了combine列表的process部分。
至于如何从豆列得到列表，那是回头另一次推送的内容，不要着急~

# 

总结一下
- 因为时间上我们各个模块的功能是独立的，因此完全可以分步测试和更新代码。
- 用最小输入测试代码段，可以简化debug过程
- 一个独立函数/功能的产生，是一个值得庆贺的过程！完全应该用 git push 进行庆祝，让大家看到并为你喝彩 :)

**Comment by bonjourup** [comment]
为腿长喝彩，这是说实现两个豆列去重合并了？多个豆列，去重合并呢？试着在腿长代码上进行添加后测试运行。

多个豆列，可以用递归函数实现。加入手动输入未知数列时出现错误。后改不用数列形式输入结果正确。

```
list_1 = ['a','b','c']
list_2 = ['b', 'd']
list_3 = ['d','b','e','f']
list_raw_input = raw_input()

def combine(list1, list2):
list_combine = list1
#list_combine 以其中一个豆列为基准与另一个豆列进行比较后，若有不同则加上，没有不同还为本身
for i in list2:
    list_combine.append(i)
remove_duplicate_element(list_combine) 
return list_combine

def remove_duplicate_element(list):
    i = 0
    while i <= len(list) - 1:
    j = i + 1
    while j <= len(list) - 1:
        if list[i] == list[j]:
            del list[j]
        j += 1
    i += 1

print combine(combine(list_1, list_2), list_3)
x = combine(combine(list_1, list_2), list_3)

print combine(x, list_raw_input)
```

 运行结果  

> qert  
> ['a', 'b', 'c', 'd', 'e', 'f']  
> ['a', 'b', 'c', 'd', 'e', 'f', 'q', 'r', 't']

#### 问题：为什么 我输入[a, u, i] 结果是这样的？

> [a, u, i]
> ['a', 'b', 'c', 'd', 'e', 'f']
> ['a', 'b', 'c', 'd', 'e', 'f', '[', ',', ' ', 'u', 'i', ']']

**Comment by nicetag** [comment]
感觉是过程跟想要的结果不一致？除了开头跟打印的部分，并没有把list_3放进来？虽然朱同学的版本我这里其实没运行成功嗷

**Comment by nicetag** [comment]
list_a = ['a','c','q']
list_b = ['c','e','q','z']

def common(list1,list2):
    list_common = []  
    for i in list1:
        for j in list2:
            if j == i:
               list_common.append(j)
               print list_common

print list_a  
print list_b  
print common(list_a,list_b)  # 出来的本应该是['c', 'q']，但因为我的哑巴英语很久没有纠正，所以返回了None。。

**Comment by mofhu** [comment]
``` python
list_a = ['a','c','q']
list_b = ['c','e','q','z']

def common(list1,list2):
    list_common = []

    for i in list1:
        for j in list2:
            if j == i:
                list_common.append(j)
    return list_common

print list_a

print list_b

print common(list_a,list_b)
```

另外, 由于 py 用缩进表示代码块, 代码段一定要用 ``` code ```包起来, 建议写:
```python
code
```
这样自带语法高亮

**Comment by mofhu** [comment]
大家的代码段都很好,为什么不增补到 repo 中呢!
要知道错误的代码也不妨推送到开发分支, 这样别人可以直接在某几行写评论/帮助修改的呀!

**Comment by mofhu** [comment]
把大家的代码增补到了function1 MVP中
b8413db403d53c2edf4adf4e83b497827dfbdd6e
