### ISSUE TITLE
Improvements needed

### ISSUE THREAD

**Issue by mofhu** [Frank-the-Obscure/iDoulist#16]
```
只是,没有给出真正的能令没动手的开始动手的方法哪?!

俺建议,腿长,
可以在两个方面,给出细碎的任务:
- 已经完成的代码基础上的小功能追加
- 新功能的不同方向方案的探索任务

这样,成员都才能真正进入工程空间.

祝顺利, 团队中,怕的不是有的慢有的快,
而是加入不能
```

被大妈的建议鼓舞, 开此 issue 鼓励大家进行第一行代码的输出, 这里列出的待实现功能也许不是那么复杂, 但对于一个项目来说, 并没有哪部分比其它部分重要. 这些功能同样是我们的作品的重要部分, 但很适合上手: **希望小伙伴们能用这些内容写下自己在 iDoulist 中的第一行代码, 第一个函数** :smile: 
- [x] 中文提示及输出优化: 功能 0 的一切 UI 提示和输出文档都是英文, 对于我们的用户而言并非是好选择, 有必要优化为更易于使用的结构, 包括以下可能的优化:
  - [x] UI 中的中文提示
  - [x] 输出文档和 CLI 中的中文提示
  - [x] 输出文档的格式优化
  - tips: print 函数的各种使用姿势可参考[笨办法学 Python 5-9](http://sebug.net/paper/books/LearnPythonTheHardWay/)
- [x] 输入输出鲁棒性(robustness)优化
  - 目前原型面对很多特别输入输出情况还没有准备, 包括而不限于`错误的链接`, `空豆列`, ...
  - 在已有输入输出函数中增加判断语句, 增强代码的鲁棒性
  - tips: [笨办法学 python 条件语句](http://sebug.net/paper/books/LearnPythonTheHardWay/ex30.html),  [Python正则表达式操作指南](http://wiki.ubuntu.org.cn/Python%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F%E6%93%8D%E4%BD%9C%E6%8C%87%E5%8D%97)

**Comment by mofhu** [comment]
周三晚半程 QC 增补:
- [x] 两个豆列作差的函数(可帮助我们实现: `这个豆列里面哪些书我没看过?`)

``` python
def subtract(list_a, list_b) # 两个列表变量
    some process??
    return list_sub #返回两个列表之差
```

常识化思路: 什么是两个列表之差?----list_a 有, 并且,list_b 没有?----如何用代码表示这样的元素?----遍历列表 a 的每一个元素, 在列表 b 中搜索, 如果没有找到, 就加入 list_sub?

**Comment by huhu8** [comment]
看了提示，百度了一下：
```python
   def  subtract(list_a, list_b)
             ret = [ ]
             if i in list_a:
             i not in list_b:
          list_sub = ret.append[i]
          return list_sub
```

**Comment by bonjourup** [comment]
根据提示，百度之后，抄袭了代码如下

``` python
a = [1,2,3,5,6]
b = [2,3]

def subtract(a, b):
    list_sub = [i for i in a if i not in b]
    return list_sub

print subtract(a, b)
```

经测试可用

**Comment by bonjourup** [comment]
求教！我抄袭的这段代码

``` python
a = [1,2,3,5,6]
b = [2,3]

def substract(a,b):
    rest = []
    for i in a:
        if i not in b:
            list_sub = rest.append(i)
            return list_sub
    print list_sub
```

运行结果：
没有任何返回值。
当将print语句改为

``` python
print substract(a,b)
```

运行结果为：
none

为什么？为什么？

**Comment by bonjourup** [comment]
``` python
a = [1,2,3,5,6]
b = [2,3]

ret = list(set(a) ^ set(b))
print ret
```

这段代码运行正常。

**Comment by mofhu** [comment]
@huhu8 :+1: 
增补到代码仓库中？
另外，在issue中的讨论似乎不方便做针对每行代码的评论，增补到仓库分支中，我们可以对每一行代码写评论，会方便很多！

**Comment by nicetag** [comment]
``` python
# print list_sub
a = [1,2,3,5,6]
b = [2,3]

def substract(a,b):
    rest = []
    for i in a:
        if i not in b:
            rest.append(i)
    return rest
print substract(a,b)
```

好像细酱婶儿滴。但是b如果不完全包含于a也灵吗？猜猜你为啥也没有push到分支里面去，是不是和我一样不知道往哪里push以及push的姿势是怎样滴。。

**Comment by mofhu** [comment]
本地随便建个分支
`git push origin master` 改成 `git push origin <your branch name>`即可
祭出廖雪峰的 git 教程= =

**Comment by bonjourup** [comment]
哇，我刚看到脆鸡的回复，多谢！

**Comment by mofhu** [comment]
commmit: a53726060ed56cbed7947e8240c377cd5d773f13
增加了中文 GUI 支持, 并对输出稍有优化

**Comment by mofhu** [comment]
commit: 9e165aa1ff711ca4d7f8744185ee91dfa3643a1a
检验输入链接格式
