### ISSUE TITLE
读取书名和其它信息

### ISSUE THREAD

**Issue by mofhu** [Frank-the-Obscure/iDoulist#22]
导入豆列时同时读取书名，或通过书籍链接进一步抓取其它信息。
i：豆列链接或者书籍链接列表
o： 书名（或者还包括作者等）列表

**Comment by mofhu** [comment]
与之相伴的另一个开发内容: 实现搜索指定书是否在豆列, 及读取其评语.

对应我们的一个实际需求, 即在超长豆列(如开智群的几个豆列)里看看有没有某本书, 当时推荐语是什么.

**Comment by zshaolin** [comment]
冒个泡，表示再次开始分析代码～～

**Comment by mofhu** [comment]
!
gl hf :+1:

**Comment by nicetag** [comment]
哇
