### ISSUE TITLE
输出到豆列: 更快

### ISSUE THREAD

**Issue by mofhu** [Frank-the-Obscure/iDoulist#23]
目前输出模块基于 pyautogui 模拟鼠标键盘操作, 依赖于浏览器的反应速度, 长豆列的输出相当慢(一分钟5本书左右, 100本就需要20分钟).
有必要提高输出到豆列的速度.

如何实现:
- 并行: 同时输出 n 个窗口
- 改变输出模式: 键盘鼠标操作本质上还是通过浏览器给豆瓣发操作, 为何不直接发操作呢?

**Comment by ZoomQuiet** [comment]
俺提示过:

无头浏览器

嗯啍

在 2015年5月24日 下午7:19，Frank Hu notifications@github.com写道：

> 目前输出模块基于 pyautogui 模拟鼠标键盘操作, 依赖于浏览器的反应速度, 长豆列的输出相当慢(一分钟5本书左右, 100本就需要20分钟).
> 有必要提高输出到豆列的速度.
> 
> 如何实现:
> - 并行: 同时输出 n 个窗口
> - 改变输出模式: 键盘鼠标操作本质上还是通过浏览器给豆瓣发操作, 为何不直接发操作呢?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Frank-the-Obscure/iDoulist/issues/23.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by mofhu** [comment]
啊哈 大妈又一次提示.  收到:)

**Comment by ZoomQuiet** [comment]
不过,这种情景中,
的确,模拟人工行为的可能就不行了,
但是,基于网页 dom 的测试框架也是有的

2015-05-25 13:43 GMT+08:00 Frank Hu notifications@github.com:

> 啊哈 大妈又一次提示. 收到:)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Frank-the-Obscure/iDoulist/issues/23#issuecomment-105132663
> .

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by mofhu** [comment]
运用常识分解添加豆列过程:
input: 鼠标键盘操作
process: 豆瓣处理为网页操作
output: 豆列添加新内容

前面版本直接模拟用户鼠标键盘操作, 导致速度受到`浏览器响应操作速度`的限制. 且受到只有一个鼠标键盘的限制, 这一操作不能简单并行.
过程中process-output完全由豆瓣服务器端决定, 本地无法进行优化. 因此想要提高速度, 应当把目标放在input上面. 

通过chrome 开发者工具测试豆列页, 发现豆列的添加内容按钮似乎是通过对象可见性显示的. (参考:[通过javascript控制div弹出，属于原来的页面，不存在父子关系，现在最流行的弹窗方式](http://blog.csdn.net/Cataleya/article/details/41478875))
![image](https://cloud.githubusercontent.com/assets/11144135/7812514/901e649a-03e5-11e5-88b5-0a844c23a802.png)

设置断点逐步操作, 发现过程中牵扯四个js文件.

尝试暂告一段落.

原则上, 通过直接发送浏览器操作(如修改上述代码段的url-input内容并发送`获取网页内容`操作, 应可实现与操作键盘鼠标完全相同的效果. 
原因是网页信息流中, 键盘鼠标-(修改网页内容并发送-)process-output. 

后续, 如何模拟这一(js?)操作?

参考[python+selenium前端测试自动化](http://blog.csdn.net/Cataleya/article/details/41478875), 也许可考虑使用这个框架操作. 另外的参考: http://www.cnblogs.com/fnng/archive/2012/01/12/2321117.html
具体到项目中, 本质上, iDoulist 只需要寻找单一按钮并进行操作, 也许无需这么大的自动化测试框架. 继续耐心使用chrome 开发者工具, 定位应该输出的 DOM 及其内容, 使用Python直接进行网页输出也许就足够了.

问题:
针对目前开发现状, 我打算用 python 模拟一段 javascript 操作, 实现自动化添加(并且比鼠标键盘操作快得多). 这个方案是否可行?

**Comment by mofhu** [comment]
20150527晚中期质控
针对我自己负责的加速输出问题. 我这两天又仔细考虑了一下: 长豆列输出对于最终产品而言并不一定是个很强的需求. 时间有限, 也许我们应该先做其它功能, 如果还有时间再做这个. 
另外技术上, 如果用 python 直接访问, 又要面对登陆豆瓣用户等新问题. 作为本地产品, 用户使用起来, 也未见得比模拟键盘鼠标(把登陆问题甩给了用户)方便.
总结一下我的中期质控:
初步尝试加快豆列输出并不成功; 技术原则上可解决, 但需要大量时间; 重新考虑产品需求, 这一功能未必如此重要. 本周暂停这个功能开发, over

**Comment by ZoomQuiet** [comment]
点赞!

2015-05-28 13:13 GMT+08:00 Frank Hu notifications@github.com:

> Closed #23 https://github.com/Frank-the-Obscure/iDoulist/issues/23.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Frank-the-Obscure/iDoulist/issues/23#event-315635231.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!
