### ISSUE TITLE
最后的开发内容

### ISSUE THREAD

**Issue by mofhu** [Frank-the-Obscure/iDoulist#26]
第三次演示过后, 大约还剩4-5天开发时间. 
这段时间我们要完成的内容有哪些? 
- 产品还有哪些功能值得开发?
- 小组产生哪些教程?
- 如何演示?
  等等

除了微信之外, 我们也可以在此讨论.

Frank
20150530

**Comment by mofhu** [comment]
产品开发方面:
- [x] 整合现有代码
- [x] 完整产品测试, 并整理出标准输入输出实例
- [x] 重写 readme, 整理使用文档和标准输入输出实例作为用户手册

**Comment by mofhu** [comment]
演示方面:
- [x] 概述: 准备 slides, 文案
- [x] 产品演示: 准备测试用例, 长例子应考虑截屏或提前录制视频(可模仿apple 发布会的模式)
- [x] 教程/开发经验: (?) 准备 slides/文案
- [x] 预案

**Comment by mofhu** [comment]
教程方面:  基本使用姿势
- [x] re 
- [x] PyAutoGUI
- [x] Word cloud

**Comment by nicetag** [comment]
见过仁波切给电视台和出版社安利他的项目。形式不一定很酷炫，但要展示项目本身意义的高大上呐，说明意义的时候可以用图片，看着比较直观。

**Comment by mofhu** [comment]
@nicetag 嗷, 明天晚上初稿给大家讨论

**Comment by mofhu** [comment]
演示完毕.

[产品视频](http://v.qq.com/page/w/t/7/w0155uqmkt7.html)

**Comment by mofhu** [comment]
其它演示资源总结等增补中
