### ISSUE TITLE
还有其它中文字体可以选择吗？

### ISSUE THREAD

**Issue by ghost** [Frank-the-Obscure/iDoulist#31]
正在学着用word_cloud生成标签云，看到例子里用的字体是WeibeiSC-Bold.otf，想试一下别的字体，但是看pil的文档没有，请问怎么可以找得到？谢谢大大！

**Comment by mofhu** [comment]
[iDoulist 教程: 如何生成豆列标签云?](https://github.com/Frank-the-Obscure/iDoulist/wiki/iDoulist-Guide:-how-to-generate-tag-cloud)

使用细节:
- 需要替换 iDoulist/output/output_tag_cloud.py 中的字体目录(line 66)和字体名称(line 74)
- /Users/FrankHu/Library/Fonts/WeibeiSC-Bold.otf 替换成自己的字体目录 (OS X 下/Users/username/Library/Fonts/)和字体文件(支持 otf/ttf)

可以试试看.

**Comment by ghost** [comment]
可是我Library/Fonts/底下是空的，我用的是OS X.

**Comment by mofhu** [comment]
只要把你想用的字体文件准备好, 字体所在目录加到 path 里面就可以, 不一定要放在同一个目录.
otf/ttf 格式应该都可用.

调用 WordCloud 时候用 font_path 指定参数. 如下所示

wordcloud = WordCloud(font_path='WeibeiSC-Bold.otf', width=800, height=400,
max_words=100,
max_font_size=250).generate_from_frequencies(frequencies).to_file('iDoulist_tag_cloud.png')
​

_Mo Hu_

_Laboratory of Mass Spectrometry and Bacterial PathogenesisInstitute of
Analytical Chemistry and *_Synthetic and Functional Biomolecules Center*

_College of Chemistry and Molecular EngineeringPeking University_
_+86-10-62766955_

2015-11-21 12:28 GMT+08:00 rylanchiu notifications@github.com:
