### ISSUE TITLE
此程序必须是python3以上版本才能跑吗？

### ISSUE THREAD

**Issue by Linkding** [Frank-the-Obscure/iDoulist#32]
我环境python2.7.1，pyobjc-core、pyobjc、pyautogui无法正常安装，是版本太低吗

**Comment by mofhu** [comment]
Hi, 

py3 依赖的原因是 py3 和 py2 对 Unicode 字符的处理不同，应该不会导致你说的无法安装的问题。建议你看一下 pyautogui 的安装文档。
你的系统环境是 OS X 吗？

Frank 

Send from cellphone.

Mo Hu
Laboratory of Mass Spectrometry and Bacterial Pathogenesis
Institute of Analytical Chemistry and Synthetic and Functional Biomolecules Center
College of Chemistry and Molecular Engineering
Peking University

**Comment by lllinx** [comment]
sorry 描述有误：

**Comment by lllinx** [comment]
sorry，描述有误：

**Comment by Linkding** [comment]
增加问题描述：安装无果是，在Linux系统下（centos6.5），使用pip下载；报错：Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QS7Ugw/pyautogui

**Comment by mofhu** [comment]
pyautogui 在 Linux 下不需要安装 pyobjc (objc 只是 OS X 需要), 详见 pyautogui 的文档

https://pyautogui.readthedocs.org/en/latest/install.html

**Comment by Linkding** [comment]
Frank,千辛万苦，搞定了DISPLAY的系统变量，重新编译python，搞定tkinter库，终于安装好了pyautogui！以为终于可以使用程序了，
但是执行安装iDoulist.py,又挂了。。。。。。。

> [root@lin iDoulist]#  python iDoulist.py 
> Traceback (most recent call last):
>   File "iDoulist.py", line 97, in <module>
>     doulist_input1 = ttk.Entry(mainframe, width=25, textvariable=url1)
>   File "/usr/local/lib/python2.7/lib-tk/ttk.py", line 667, in **init**
>     Widget.**init**(self, master, widget or "ttk::entry", kw)
>   File "/usr/local/lib/python2.7/lib-tk/ttk.py", line 555, in **init**
>     Tkinter.Widget.**init**(self, master, widgetname, kw=kw)
>   File "/usr/local/lib/python2.7/lib-tk/Tkinter.py", line 2090, in **init**
>     (widgetName, self._w) + extra + self._options(cnf))
> _tkinter.TclError

遍寻了stackoverflow，还是无果

我使用centos6.4，python2.7.1，ssh终端是xshell。

**Comment by mofhu** [comment]
不知道你如何分析这个问题, 在我看来这是 tk 出了问题, 还没到 iDoulist 会不会出问题的时候... 
我会抛开 iDoulist 先不看, 用比较简单的 tk/ttk 脚本测试 tk 是否正常可用.
不妨先试试 [`这里的简单代码`](https://github.com/mofhu/omooc-pythoncamp0/blob/caaf4042f0301b851e8ac6bf52b5493afa13ae7c/source/week10/tkinter.md#第三种画法-ttk), 如果 tk/tcl 还是报错, 就先试着解决 tk 的问题吧.

另外, 我刚刚发现前面的讨论中我说的有错误, [iDoulist 是在 2.7.9 下开发和测试的](https://github.com/mofhu/iDoulist#如何安装), 因此应该不存在 py3 的问题(最近一直在用 py3, 搞混了请见谅).

gl

**Comment by Linkding** [comment]
谢谢frank的提示

**Comment by mofhu** [comment]
Guess it may be closed, feel free to reopen
