### ISSUE TITLE
#4爱豆列 需求讨论：1、2、3条的讨论

### ISSUE THREAD

**Issue by bonjourup** [Frank-the-Obscure/iDoulist#4]
- 1.为什么要在豆列中找书？在豆列中找书，是已经知道书名了吗？

我理解的在豆列中找书是，我不知道书的名字，我只是想看看有哪些书是豆列作者推荐的书，然后我找来阅读。不知是否正确？
- 2.为什么要比较豆列是否重叠？一部分书重叠是豆列的常态。那么是要筛查全部重叠？

利用别人的豆列建立自己的豆列，如果能打标签标注豆列出处，这样就可以**“结构化”**处理豆列。也有助于发现优质内容。
- 3.导出豆列的形式是：

豆瓣的豆列刚刚用了一下，感觉就像书签类网站！比如delicious，不同的是delicious没有书目列表，delicious没有用过导出功能，像浏览器自带的书签功能，一般导出是html形式，有文件夹标题，然后是书签文件夹里详细的各标题链接内容。

个人认为导出html形式，不太方便整理。如果能导出excel格式的，是最好的。尤其是对书籍类豆列。
这样就可以筛选和排序数据。

（刚发现，豆瓣豆列有浏览器插件，当你在网上发现了什么好的内容需要收藏以方便回看时，可以直接点击浏览器插件就会添加到你指定的豆列里了）

**Comment by mofhu** [comment]
都是非常好的问题, 如果没有用的话,这些功能就不必做了, 所以一开始讨论清楚是很重要的. 
但是很遗憾我自己说的不明白,所以再解释一下:
1. 我的找书有几个情况: 
   - 想知道某本书在某豆列里是否提到
   - 想把某豆列的书按其它方式 (如标签) 整理
   - 特别是在开智书单这种10+页的列表时, 处理起来就很麻烦.
2. 举一个实际例子:
   - 我想看看开智书单有多少书是我已经看过的. 顺便把没看过的书单独放置另一个豆列中
   - 我留存了一个看过的书的列表
   - 这时以目前条件手动, 只有一个办法,就是挨个看自己的每一本书是不是有.
   - 如果可以比较是否重叠...会方便很多?
3. 导出形式:
   - 最简单是导出到文件, 如你所说, excel 等等
   - 稍复杂是导出到另一个豆列,如2中, 如果我们能实现导出到豆列,那么就轻松愉快, duang 一下子, 得到了没看过的书单

**Comment by mofhu** [comment]
我们需要进一步讨论吗? 如果问题已经解决, 请考虑 close issue @huhu8
