### ISSUE TITLE
Process

### ISSUE THREAD

**Issue by mofhu** [Frank-the-Obscure/iDoulist#5]
已有 std input, 参考 issue #2 给出的输入结果, 通常是一个列表

Process 的目的是: 写出一系列函数,实现各种任性的豆列操作功能:
- 合并豆列
- 计算两个豆列的 交/并/补
- 任性添加自己想要的功能

**Comment by bonjourup** [comment]
初步想了一下，
- 合并豆列是不是就是 针对豆列（列表）的合并，抽象书列中书的条目为一个list（不对，应该是元组？），每条元组为一个元素，然后为一个数列list，然后list的合并？
- 计算list是不是重复，这个脑袋里还没有一点知识印象。（这会腿长让捉急的。我也捉急，汗）
- 任性添加，待我想想：生成新的豆列？或者？

**Comment by mofhu** [comment]
@huhu8 具体实例我昨天已经给出了，可能乎乎没有看到。建议参考这个构建最初原型：
https://github.com/Frank-the-Obscure/iDoulist/blob/master/stdio-function0.md
https://github.com/Frank-the-Obscure/iDoulist/wiki/iDoulist-Plan-week-1

**Comment by mofhu** [comment]
https://gist.github.com/Frank-the-Obscure/a75bf00ab2f171830af2#file-function0-process-py
